### ISSUE TITLE
Linkit update via composer on Craft 3

### ISSUE THREAD

**Issue by mikewink** [fruitstudios/craft-linkit#100]
I would like to know how to update Linkit to 3.x with composer? I do not use the Craft backend to update.

In the release details, I see the version bump to v3, and transfer of ownership, but after running `composer update --with-all-dependencies` the update is still there and my composer.json still shows the `"fruitstudios/linkit": "^1.1.12.1"` version entry. So, nothing has changed. 

What's the right process to upgrade without losing the fields (and settings)? 

Thank you

**Comment by samhibberd** [comment]
You should be able to update your composer.json file with the new package name and run install, please test this locally before doing anything in production!

The ownership transferred from `fruitstudios` to `presseddigital` so this should do it:

```"presseddigital/linkit": "^3.0.0"```

That how we have updated when testing the upgrade process locally, albeit with symlinked packages.

**Comment by darylknight** [comment]
This caught me out too. I saw the new version and just updated the version number in composer.json to `"fruitstudios/linkit": "^3.0.0",`. Changing the package owner fixes the issue, thanks Sam.

As an aside - it might be worth adding some patch notes? My Updates section just says "Linkit 3.0.0" and nothing else.

![image](https://user-images.githubusercontent.com/1250017/180170169-24878141-1689-43c0-a425-fa8988f3c041.png)

**Comment by samhibberd** [comment]
Thanks @darylknight, just seen this, no idea why (might be related to the ownership transfer - wish we have just left it where it was!!!). Will work that out and get it fixed up as well as adding some manual update notes.

**Comment by mikewink** [comment]
I did update `composer.json` as suggested and the update/upgrade process worked as always. 

I was reminded to run migrations when entering the backend. When I ran the command, I got the following message:

```
Checking for pending migrations ...
Total 0 new Linkit migrations to be applied:

Apply the above migrations? (yes|no) [no]:yes
Create database backup? (yes|no) [yes]:yes
Backing up the database ... done
```

The website is running as before, the fields are there and working! I will close this issue.

**Comment by jamesmacwhite** [comment]
After changing the composer.json dependency, I get this error

```
Linkit is installed with schema version of 1.2.0 while 1.0.8 was expected.
```

I was running the older fruitstudios linkit and this site was also from Craft CMS 2, not sure if that's relevant.

I could manually modify the schema version, but just posting in case there's a better way.

Edit: Looks like project.yaml changes hadn't written the schemaVersion when replacing the plugin, possibly due to write permissions as WSL2 and Nitro tends to have issues with permissions on files.
