### ISSUE TITLE
Error updating Linkit from 1.1.12.1 to 3.0.0

### ISSUE THREAD

**Issue by JJefferyDev** [fruitstudios/craft-linkit#101]
Hello, 
I have completely deleted then reinstalled the vendor directory, then I attempted the update from Linkit 1.1.12.1 to 3.0.0, and this is the error I get:
----------------------------------------------------------- 
Status: Internal Server Error 
Response: {"error":"Class \"fruitstudios\\linkit\\services\\LinkitService\" not found","exception":"Error","file":"D:\\inetpub\\wwwroot\\bcogc-new\\plugins\\bcogc\\bcogc-extras\\src\\BcogcExtras.php","line":131,"trace":[{"file":"D:\\inetpub\\wwwroot\\bcogc-new\\vendor\\yiisoft\\yii2\\base\\BaseObject.php","line":109,"function":"init","class":"bcogc\\bcogcextras\\BcogcExtras","type":"->"},{"file":"D:\\inetpub\\wwwroot\\bcogc-new\\vendor\\yiisoft\\yii2\\base\\Module.php","line":161,"function":"__construct","class":"yii\\base\\BaseObject","type":"->"},{"file":"D:\\inetpub\\wwwroot\\bcogc-new\\vendor\\craftcms\\cms\\src\\base\\Plugin.php","line":115,"function":"__construct","class":"yii\\base\\Module","type":"->"},{"function":"__construct","class":"craft\\base\\Plugin","type":"->"},{"file":"D:\\inetpub\\wwwroot\\bcogc-new\\vendor\\yiisoft\\yii2\\di\\Container.php","line":419,"function":"newInstanceArgs","class":"ReflectionClass","type":"->"},{"file":"D:\\inetpub\\wwwroot\\bcogc-new\\vendor\\yiisoft\\yii2\\di\\Container.php","line":170,"function":"build","class":"yii\\di\\Container","type":"->"},{"file":"D:\\inetpub\\wwwroot\\bcogc-new\\vendor\\yiisoft\\yii2\\BaseYii.php","line":365,"function":"get","class":"yii\\di\\Container","type":"->"},{"file":"D:\\inetpub\\wwwroot\\bcogc-new\\vendor\\craftcms\\cms\\src\\Craft.php","line":61,"function":"createObject","class":"yii\\BaseYii","type":"::"},{"file":"D:\\inetpub\\wwwroot\\bcogc-new\\vendor\\craftcms\\cms\\src\\services\\Plugins.php","line":948,"function":"createObject","class":"Craft","type":"::"},{"file":"D:\\inetpub\\wwwroot\\bcogc-new\\vendor\\craftcms\\cms\\src\\services\\Plugins.php","line":232,"function":"createPlugin","class":"craft\\services\\Plugins","type":"->"},{"file":"D:\\inetpub\\wwwroot\\bcogc-new\\vendor\\craftcms\\cms\\src\\base\\ApplicationTrait.php","line":1486,"function":"loadPlugins","class":"craft\\services\\Plugins","type":"->"},{"file":"D:\\inetpub\\wwwroot\\bcogc-new\\vendor\\craftcms\\cms\\src\\web\\Application.php","line":99,"function":"_postInit","class":"craft\\web\\Application","type":"->"},{"file":"D:\\inetpub\\wwwroot\\bcogc-new\\vendor\\yiisoft\\yii2\\base\\BaseObject.php","line":109,"function":"init","class":"craft\\web\\Application","type":"->"},{"file":"D:\\inetpub\\wwwroot\\bcogc-new\\vendor\\yiisoft\\yii2\\base\\Application.php","line":204,"function":"__construct","class":"yii\\base\\BaseObject","type":"->"},{"function":"__construct","class":"yii\\base\\Application","type":"->"},{"file":"D:\\inetpub\\wwwroot\\bcogc-new\\vendor\\yiisoft\\yii2\\di\\Container.php","line":419,"function":"newInstanceArgs","class":"ReflectionClass","type":"->"},{"file":"D:\\inetpub\\wwwroot\\bcogc-new\\vendor\\yiisoft\\yii2\\di\\Container.php","line":170,"function":"build","class":"yii\\di\\Container","type":"->"},{"file":"D:\\inetpub\\wwwroot\\bcogc-new\\vendor\\yiisoft\\yii2\\BaseYii.php","line":365,"function":"get","class":"yii\\di\\Container","type":"->"},{"file":"D:\\inetpub\\wwwroot\\bcogc-new\\vendor\\craftcms\\cms\\src\\Craft.php","line":61,"function":"createObject","class":"yii\\BaseYii","type":"::"},{"file":"D:\\inetpub\\wwwroot\\bcogc-new\\vendor\\craftcms\\cms\\bootstrap\\bootstrap.php","line":247,"function":"createObject","class":"Craft","type":"::"},{"file":"D:\\inetpub\\wwwroot\\bcogc-new\\vendor\\craftcms\\cms\\bootstrap\\web.php","line":51,"function":"require"},{"file":"D:\\inetpub\\wwwroot\\bcogc-new\\web\\index.php","line":20,"function":"require"}]}

**Comment by samhibberd** [comment]
Hi @JJefferyDev, the namespace change should have been handled by the update so no sure exactly what's going on here. 

Could you provide a little more detail on the steps that caused you to run into this error?

**Comment by JJefferyDev** [comment]
Hi, I figured out the error, a different custom plugin a different
developer made was causing the issue. Everything is fixed now.

**Comment by samhibberd** [comment]
Thanks for the update.
