### ISSUE TITLE
presseddigital\linkit\base\ElementLink::getUrl(): Return value must be of type string, null returned

### ISSUE THREAD

**Issue by Troops994** [fruitstudios/craft-linkit#107]
Getting the following errors for Linkit.

Strill seeing an issue where the type string is referenced.

in /var/www/craft/vendor/presseddigital/linkit/src/base/ElementLink.phpat line 71
62636465666768697071727374757677787980        if (!is_null($this->customSelectionLabel) && $this->customSelectionLabel != '') {
            return $this->customSelectionLabel;
        }
        return $this->defaultSelectionLabel();
    }
 
    public function getUrl(): string
    {
        $element = $this->getElement();
        return $element ? $element->getUrl() : '';
    }
 
    public function getText(): string
    {
        return $this->getCustomOrDefaultText() ?? ($this->getElement() ? $this->getElement()->title : null) ?? $this->getUrl() ?? '';
    }
 
    public function getElement()
    {
2. in /var/www/craft/vendor/yiisoft/yii2/base/Component.php at line 139– presseddigital\linkit\base\ElementLink::getUrl()
3. in /var/www/craft/vendor/craftcms/cms/src/helpers/Template.php at line 90– [yii\base\Component::__get](http://www.yiiframework.com/doc-2.0/yii-base-component.html#__get()-detail)('url')
84858687888990919293949596 
        if (
            $type !== TwigTemplate::METHOD_CALL &&
            $object instanceof BaseObject &&
            $object->canGetProperty($item)
        ) {
            return $isDefinedTest ? true : $object->$item;
        }
 
        // Convert any \Twig\Markup arguments back to strings (unless the class *extends* \Twig\Markup)
        foreach ($arguments as $key => $value) {
            if (is_object($value) && get_class($value) === Markup::class) {
                $arguments[$key] = (string)$value;

**Comment by Troops994** [comment]
This issue seems to be only with Entries, I think it is the one you might be already investigating.

**Comment by Troops994** [comment]
Morning, any idea when the fix will be out, this is effecting our live environments so we are keen to get this resolved asap.

**Comment by andrewfairlie** [comment]
Any update on this?

**Comment by ben-callaway** [comment]
Fixed in 3.0.3 / 4.0.3
