### ISSUE TITLE
Element Url Bug if no Element is given (in new Release 3.0.3)

### ISSUE THREAD

**Issue by lukasNo1** [fruitstudios/craft-linkit#109]
With this commit, the plugin now throws an error, if the element is null (Error: Call to a member function getUrl() on null)

Can you readd the element check?
https://github.com/presseddigital/linkit/commit/0c53873d2bfdd71289872453857e8dfacde896e0

**Comment by ben-callaway** [comment]
Thanks - updated in latest release.
