### ISSUE TITLE
Craft 5 version

### ISSUE THREAD

**Issue by russclewett-mw** [fruitstudios/craft-linkit#114]
Hi there

Is there a plan to update the Linkit plugin to Craft 5?

Cheers

**Comment by samhibberd** [comment]
Yes for sure!!

**Comment by russclewett-mw** [comment]
Ahh that's good to hear, I don't suppose you have a timeframe on it?

**Comment by pbd-dev** [comment]
Just following up on this, any idea of a timeframe for Craft 5 version?

**Comment by pappgergely** [comment]
We're also planning to use this plugin in an upcoming Craft 5 project. Could you provide an estimated timeline so we can plan accordingly? Thanks.

**Comment by ben-callaway** [comment]
We're in final testing and will be releasing the update imminently. Thanks for the patience!

**Comment by ben-callaway** [comment]
Released 🎉 Thanks for hanging in there! https://github.com/presseddigital/linkit/tree/v5
