### ISSUE TITLE
Default text doesnt seem to out put

### ISSUE THREAD

**Issue by keithmancuso** [fruitstudios/craft-linkit#16]
for some reason the default text on our links werent outputting. We had it say learn more by default on a matrix field but instead of saying that it was the title of the element it was linking to when i ouput

`{{block.ctaLink.text}}`

but loving the plugin so far, solves so many problems

**Comment by samhibberd** [comment]
Hmm I think that’s a big, the value for default text should only be overridden should custom text be enabled and set on the field. That sound right??  

Great to hear your enjoying it!!

**Comment by samhibberd** [comment]
Fixed in [v1.0.6 ](https://github.com/fruitstudios/craft-linkit/releases/tag/v1.0.6)
