### ISSUE TITLE
Javascript for showing entry select button when multiple linkit fields are in the same entry doesnt work

### ISSUE THREAD

**Issue by davecosec** [fruitstudios/craft-linkit#18]
Javascript for showing entry/asset select button when multiple linkit fields are in the same entry doesnt work. It just hides and shows the entry/asset select button next to the first field

**Comment by davecosec** [comment]
I forked the project and essentially added the input handle to the beginning of the field name then removed it on save. it seems to work but I haven't had time to test it.

**Comment by samhibberd** [comment]
Thanks for reporting (and forking) we will get it fixed in the next release.

**Comment by samhibberd** [comment]
Fixed in [v1.0.6 ](https://github.com/fruitstudios/craft-linkit/releases/tag/v1.0.6)
