### ISSUE TITLE
Drop down menus not displaying previous value

### ISSUE THREAD

**Issue by davecosec** [fruitstudios/craft-linkit#20]
Drop down menus are not displaying previous value.

**Comment by davecosec** [comment]
https://github.com/davecosec/craft-linkit/commit/bb6fcf2c52a9e4560cc82b112e5fbbb05dc4fbce

**Comment by samhibberd** [comment]
@davecosec can you provide a bit more info on this one, can't seem to recreate locally.

**Comment by samhibberd** [comment]
@davecosec I have had a good test and not recreated, it all looks to be working here. Going to close this off, if you do have more info or think you have found a bug don't hesitate to open this up again. Thanks.
