### ISSUE TITLE
Multi-Site

### ISSUE THREAD

**Issue by maxstrebel** [fruitstudios/craft-linkit#23]
Hi, I'm just giving Link-It a test-run on a multi-site Craft3 Installation. I'm using it in a Matrix Field. The Problem is, that it only displays Entries from the Main Site, not the selected Site.

So if you select another Site which has different Enries, the relevant Entries are not selectable.

**Comment by sevfurneaux** [comment]
I also have the same issue, and was about to post this too 🙃

**Comment by samhibberd** [comment]
Thanks @maxstrebel will get a fix out asap!

**Comment by maxstrebel** [comment]
@samhibberd perfect, thanks!

**Comment by samhibberd** [comment]
Fixed in 1.0.8
