### ISSUE TITLE
When using Phone / Mail, text includes mailto:/tel: prefix

### ISSUE THREAD

**Issue by maxstrebel** [fruitstudios/craft-linkit#24]
Hi, I just used the phone and mail fields for the first time. I encounter the issue that when outputting them this way:

`<td><a href="{{ row.fieldHandle.url }}">{{ row.fieldHandle.text }}</a></td>`

the result looks like this

`<td><a href="tel:+49 (0) 611 304 021">tel:+49 (0) 611 304 021</a></td>`

![image](https://user-images.githubusercontent.com/910594/38978710-77f5e864-43b8-11e8-856e-f8564d9540f3.png)

Am I getting something wrong, or is this a bug?

**Comment by samhibberd** [comment]
Thanks for reporting @maxstrebel, this is a bug, fixed in 1.0.7 which will be available shortly.
