### ISSUE TITLE
Link to Documentation is wrong

### ISSUE THREAD

**Issue by maxstrebel** [fruitstudios/craft-linkit#25]
Blue link (Documentation) shown in screenshot currently leads to https://github.com/fruitstudios/craft-linkit/README.md, which is a 404 not found page.

![image](https://user-images.githubusercontent.com/910594/38983641-185c89fa-43c5-11e8-8f43-d913d06905b7.png)

![image](https://user-images.githubusercontent.com/910594/38983650-1fcdab4c-43c5-11e8-8732-5430a062de10.png)

**Comment by samhibberd** [comment]
Thanks @maxstrebel fixed in 1.0.7 which will be available shortly.
