### ISSUE TITLE
entry.fieldhandle.type returns a long string

### ISSUE THREAD

**Issue by darylknight** [fruitstudios/craft-linkit#34]
I'm trying to show a different icon depending on whether the user has selected "URL" or "Asset" for the linkit type. If I call `{{ entry.fieldhandle.type }}` in the template, I'd expect to get `url` or `asset`, but I'm getting this:

`fruitstudios\linkit\models\Url`
`fruitstudios\linkit\models\Asset`

**Comment by samhibberd** [comment]
@darylknight you can use `{{ entry.linkItField.typeHandle }}` to output a more useful type string for use in scenarios like this. Does this help?

**Comment by darylknight** [comment]
Yes, that's perfect. Sorry if I missed this and it was documented.
