### ISSUE TITLE
Loosen validation on LinkedIn links (and possibly other social links)

### ISSUE THREAD

**Issue by stevehurst** [fruitstudios/craft-linkit#36]
Currently all of these validate:
http://www.linkedin.com/in/name
https://www.linkedin.com/in/name
https://mx.linkedin.com/in/name
https://nl.linkedin.com/in/name
(as well as other country codes)

But for some reason:
https://linkedin.com/in/name

Without the 'www' doesn't validate.

These links work on LinkedIn, and are leading to a lot of confusion when our users submit a page.

**Comment by samhibberd** [comment]
This has been fixed in 1.0.9 which will be ready for release by the end of the week.
