### ISSUE TITLE
Allow mailto: links to be added as URLs

### ISSUE THREAD

**Issue by jsunsawyer** [fruitstudios/craft-linkit#41]
We would prefer to not add the specific email option and just have users manually add `mailto:test@example.com`.

Linkit used to let these be saved, but now they don't pass validation and gives the error message `Please enter a valid url.`.

**Comment by jsunsawyer** [comment]
This would also address adding anchor links without needing to add the full url. See #39

**Comment by samhibberd** [comment]
Thanks @jsunsawyer Added support for this in [1.1.5](https://github.com/fruitstudios/craft-linkit/releases/tag/1.1.5)
