### ISSUE TITLE
Crashes Solspace’s Calendar plugin

### ISSUE THREAD

**Issue by joshuabaker** [fruitstudios/craft-linkit#42]
**Steps to replicate**
1. Add LinkIt field to calendar fields
1. Load calendar view (i.e. month, week, or day)
1. Result: Infinite recursion 

| Plugin | Version |
| --- | --- |
| Solspace Calendar | 2.0.6 |
| LinkIt | 1.1.3 |

Do you have any thoughts on this?

**Comment by samhibberd** [comment]
Will get this fixed in the next release, thanks to Brad Bell.

**Comment by samhibberd** [comment]
See 1.1.4, let me know how you get on.
