### ISSUE TITLE
Assigning Value to Link Attributes from another Field

### ISSUE THREAD

**Issue by nearkingdom** [fruitstudios/craft-linkit#46]
How do we assign a value from another field to the attributes? For example, I'm wanting to use the value from a field called linkStyle to set on the link's class name {{ block.linkStyle }}

```
      {% if block.type == 'link' %}

        {% set attributes = {
          class: 'white bg-black {{ block.linkStyle }}',
        } %}
        {{ block.linkit.link(attributes) }}

      {% endif %}
```

**Comment by samhibberd** [comment]
Twig doesn't allow tags within tags, this should do it:

```
{% if block.type == 'link' %}

    {% set attributes = {
        class: 'white bg-black '~block.linkStyle,
    } %}
    {{ block.linkit.link(attributes) }}

{% endif %}

```

or just set the options directly

```
{% if block.type == 'link' %}

    {{ block.linkit.link({
        class: 'white bg-black '~block.linkStyle,
    }) }}

{% endif %}

```

**Comment by nearkingdom** [comment]
Thanks that makes sense. Is there any twig documentation on this I can read?

**Comment by samhibberd** [comment]
You can find most answers in the Twig docs:

https://twig.symfony.com/
https://twig.symfony.com/doc/2.x/templates.html

**Comment by nearkingdom** [comment]
Apologies... when I try the linkit field in a matrix within a matrix (list items) I get an error on `{{ item.itemLink.(attributes) }}`. Works fine on a first layer matrix as you documented above but not a second layer matrix for some reason.

I'm actually trying to change the link's click text so changing the 'title' attribute is likely to be the wrong thing to change but would be good to know how to do that anyway.

```
        <!-- If link style ul -->
        {% if block.listType == 'ul' %}

          <ul>
            {% for item in block.list %}
                <li>
                  {% if item.itemLink.available %}
                    {% set attributes = {
                        title: item.itemTitle,
                    } %}
                    {{ item.itemLink.(attributes) }}
                  {% else %}
                    {{ item.itemTitle }}
                  {% endif %}
                </li>
            {% endfor %}
          </ul>

        {% endif %}
```

**Comment by samhibberd** [comment]
Not sure, but his will throw an error:

`{{ item.itemLink.(attributes) }}`

Missing the link method:

`{{ item.itemLink.link(attributes) }}`

**Comment by nearkingdom** [comment]
Thanks and sorry for all these questions...

Finally, I'm getting a "Impossible to access an attribute ("link") on a null variable." The code below works until I add a list item without a link and I get the above error... is there a more appropriate way of checking if the list item has a linkit field? Currently I am using  {% if item.itemLink.available %}.

```
{% for item in block.list %}
              <li>
                {% if item.itemLink.available %}
                    {% if item.itemLink.hasElement %}
                      {{ item.itemLink.link }}
                    {% else %}
                      <a href="{{ item.itemLink.url }}" title="{{ item.itemTitle }}" target="{{ item.itemLink.targetString }}">{{ item.itemTitle }}</a>
                    {% endif %}
                {% else %}
                  {{ item.itemTitle }}
                {% endif %}
              </li>
            {% endfor %}
```

**Comment by nearkingdom** [comment]
Any thoughts on the above error?

**Comment by samhibberd** [comment]
I'm hoping to look at this today, looks to be an issue with the `.available` method, you should be able to use `{% if item.itemLink %}` to check if there is a link available.

**Comment by nearkingdom** [comment]
Yes that works. Thanks.
