### ISSUE TITLE
Cannot install in Craft 3.1 beta

### ISSUE THREAD

**Issue by ryanfoote** [fruitstudios/craft-linkit#48]
Hi,

Attempting to install the plugin in Craft 3.1.0 beta 5.1 results in the following error: `Couldn’t install plugin.` (super helpful)

I took a jaunt through the logs to see if there was an error that jumped out at me, but didn't spot anything in particular. I'd be happy to send along the log, if that'd be helpful.

**Comment by samhibberd** [comment]
@ryanfoote thanks for reporting we are aware of some issues with 3.1 and will get them fixed up asap.

**Comment by ryanfoote** [comment]
Great! Does version 1.1.5 address this install problem since Craft 3.1 was released yesterday?

**Comment by samhibberd** [comment]
1.1.6 Fixes this.
