### ISSUE TITLE
Craft 2 to 3.1 Linkit fields that are in a Super Table within Matrix data is lost

### ISSUE THREAD

**Issue by jamesmacwhite** [fruitstudios/craft-linkit#59]
@samhibberd Thanks for the updated migrations in 1.1.10, these handle Matrix/Super Table a lot better. I recently tested a fresh migration from Craft 2 with the 1.1.10 migration code with better success on various Craft 2 link fields.

I still observed data loss on Linkit fields that are in a Super Table within a Matrix (inception, right?!).

Here's an example of a field data structure to help visualise the field layout:

![image](https://user-images.githubusercontent.com/8067792/54676869-96deb280-4af9-11e9-8443-257993664d9f.png)

![image](https://user-images.githubusercontent.com/8067792/54677882-c393c980-4afb-11e9-9e3e-db11f2687907.png)

The idea is within the navigationList field you can have multiple Matrix blocks, which within the Matrix blocks is a Super Table field that can have one or more Linkit fields within that.

While the migration handles these fields and they get updated to the Craft 3 Linkit field type, the data within is completely lost from Craft 2. 

![image](https://user-images.githubusercontent.com/8067792/54677766-7fa0c480-4afb-11e9-9466-1b0d12589c3c.png)

I guess this might still relate to #53, but given this now relates more to the Super Table field side of things, I thought I'd open a new issue.

**Comment by samhibberd** [comment]
:) Fun and games, I would have though these would be caught by the matrix block logic, hmm. Can you send me a dump of the Craft 3 database before installing the new linkit?

**Comment by jamesmacwhite** [comment]
@samhibberd Sure thing. Matrix without Super Table appears to have been migrated under v1.1.10 so that's all good, I think this issue is now when it's Matrix -> Super Table -> Linkit.

Let me know where I can send the DB. Could you let me know what specific tables you are interested in and I'll do a selective export.

**Comment by samhibberd** [comment]
@jamesmacwhite will drop you a dm on Discord.

**Comment by jamesmacwhite** [comment]
@samhibberd Stand down on this one. It looks like it's Super Table related.

https://github.com/verbb/super-table/issues/255

Several of the Craft 2 Super Table database tables require fixing after installation. After running the fix tool within Super Table the Linkit fields are migrated with the existing values.
