### ISSUE TITLE
[FR] Allow to select Entries from other Sites in Entry Picker

### ISSUE THREAD

**Issue by sarahschuetz** [fruitstudios/craft-linkit#72]
In newer Craft versions the entry picker allows to select entries from other sites:
![Screenshot 2019-12-16 at 12 23 56](https://user-images.githubusercontent.com/14288451/70903670-a72bab80-1fff-11ea-987a-b4eda5055834.png)

But unfortunately when selecting an entry via Linkit it is not possible to link to entries from other sites:
![Screenshot 2019-12-16 at 12 21 32](https://user-images.githubusercontent.com/14288451/70903414-21a7fb80-1fff-11ea-80ad-ca8aab4fd26c.png)

Would be great if you could add this feature! :)

**Comment by Coalescent** [comment]
Chipping in to say from my perspective this really shouldn't be a FR, this is really a bug that should be fixed.

When configuring a LinkIt field, the CP UI allows a user to select sections/structures from **all** sites... but then as the original poster points out, there is no way to actually select entries from these other site sections/structures.

Further, when using this field as a Global, you can _only_ access entries form the primary site.

**Comment by ajp** [comment]
I've just migrated a site with heavy LinkIt usage, and was surprised that this plugin doesn't allow selecting entries from other sites.

**Comment by philipzaengle** [comment]
This would be real handy. :)

**Comment by studiosyntax** [comment]
Same here, we're really missing this option in LinkIt. Any thoughts on implementing this?

**Comment by renzo-s** [comment]
Common guys, this bug is a serious show stopper. This plugin is still in the store for 40 bucks, plus 20 a year, and hasn't seen an update on over 1,5 years.

**Comment by davidhellmann** [comment]
We are also not happy. It's a paid plugin. Some infos would be nice.

**Comment by ben-callaway** [comment]
Fixed in #b3fd964
