### ISSUE TITLE
Missing link input in Craft 3.5

### ISSUE THREAD

**Issue by jerome2710** [fruitstudios/craft-linkit#79]
We have been using Linkit happily through various of our sites. However, while testing Craft 3.5-RCX, Linkit seems to be broken. We are unable to enter a link, neither through direct URLs or entries:

![Schermafbeelding 2020-07-29 om 12 09 30](https://user-images.githubusercontent.com/4600095/88787814-c0e7c080-d194-11ea-89eb-94d7be2fb93f.png)

Existing fields do show their link, but new fields are missing their inputs.

@samhibberd can you give an estimation when this issue might be solved? This is a blocker for us right now.

**Comment by samhibberd** [comment]
Can you confirm which RC you are running, we ran into some issues with our custom field types with RC4 which have been resolved in a subsequent 3.5.x commit?

**Comment by jerome2710** [comment]
The RC's are evolving a bit rapidly at the moment, we are now using the latest RC4.

**Comment by samhibberd** [comment]
Ha yes, I think our issue was actually with RC3. Will run a test with the latest and go from there.

**Comment by samhibberd** [comment]
Can confirm it's broken in RC4, will work out if it's a Craft thing or something we need to address.

**Comment by samhibberd** [comment]
@jerome2710 Fixed in the latest 3.5 https://github.com/craftcms/cms/commit/8081d5178264193629abc0bffd6677f00dec2c18

Thanks @brandonkelly
