### ISSUE TITLE
Manual installation?

### ISSUE THREAD

**Issue by presentmotion** [fruitstudios/craft-linkit#86]
Hello,

I purchased the plugin in Craft's Plugin Store, but because of my server's PHP memory limit, I cannot install via Settings -> Plugins page. Getting the "PHP Fatal error:  Out of memory" error.

Even though I upped the memory_limit in php.ini from 128M to 512M, the host (MediaTemple) support cannot reboot the shared server for the change to take effect.

Is manual installation (locally on my computer) via Composer possible at all?
I was able to do this for other (free) plugins and then simply upload the necessary files via FTP.

Thank you!

**Comment by samhibberd** [comment]
Hi @presentmotion,

Instructions on composer installation are here:

https://github.com/presseddigital/linkit#composer

Thanks
