### ISSUE TITLE
Doesn't return array in graph ql

### ISSUE THREAD

**Issue by gorelegacy** [fruitstudios/craft-linkit#96]
The linkit field doesn't return an array in the craft graph ql.

It only returns a string `"<a href="https://www.instagram.com/" target="_blank" rel="noopener noreferrer">Instagram</a>"`

instead of an array that contains the url, text, customText, target etc like you can do in twig

**Comment by samhibberd** [comment]
Hi @gorelegacy we have actually added support for Craft Graph QL in the upcoming release (along with eager support and some other stuff). 

We don’t currently use gl and as a result don’t have a great deal of experience with it. 

We have some final testing before getting the release out, but if you wanted to check out the develop branch and have a test that would be really really useful. 

Happy to chat through on Discord if you had any questions / feedback.

**Comment by JayBox325** [comment]
This is a feature I'd be very interested in getting added. Watching.

**Comment by samhibberd** [comment]
@JayBox325 if you wanted to test this feature then grab the develop branch, would value any feedback. It also includes eager loading support.

**Comment by JayBox325** [comment]
Hi @samhibberd, I'll use it on a project I'm working on at the moment.

My current approach to this though, if @gorelegacy was interested, was this helper function using `html-react-parser': 

```
import Parser from 'html-react-parser';

const buttonProps = Parser(String(button))

const {
    href,
    rel,
    target,
    children
} = buttonProps.props || {}
```

which creates the following:
![image](https://user-images.githubusercontent.com/13233809/163230927-a549e0b1-871f-4842-82b8-4526cc156b50.png)

Which I found to be a great solution for now where 'children' is my label, and the rest are all props for the a tag. Beaut.

**Comment by samhibberd** [comment]
Added with latest releases:

Craft 4: https://github.com/presseddigital/linkit/releases/tag/4.0.0
Craft 3: https://github.com/presseddigital/linkit/releases/tag/3.0.0

**Comment by JayBox325** [comment]
I updated linkit last week and thoroughly enjoyed seeing this. Didn't enjoy the timing of how it happened the day of production deployment, but it was so quick to alter my markup. Well done, great work!
