### ISSUE TITLE
Craft 4 Support

### ISSUE THREAD

**Issue by peirix** [fruitstudios/craft-linkit#97]
First off: Really love this plugin. It's included in all my projects. So, now that Craft 4 is approaching release, are you planning to have the plugin ready for that? We're just about to start a new project, and the plan is to use Craft 4, and I'd really love to have your plugin in my arsenal for that job as well (:

**Comment by samhibberd** [comment]
Plan is absolutely to support Craft 4 at release. 

Great if you would be keen to help test? Can fire over an update when we are ready.

**Comment by peirix** [comment]
Absolutely. We've actually started the development now, so just send over when you have something ready for testing, and I'll include it in our project.

**Comment by internetztube** [comment]
Same here.

**Comment by internetztube** [comment]
Do you have a rough timeline for when the first beta version of the plugin will be available? We're happy to test the beta version. @samhibberd

**Comment by jan-dh** [comment]
Can we please, please, please include an easy option to add custom classes or other attributes to links? 😇

**Comment by myleshyson** [comment]
Do ya'll still need help testing?

**Comment by jan-dh** [comment]
can help out as well!

**Comment by ryanmasuga** [comment]
We use this on many Craft sites. Would like to start updating a few to Craft 4, but this plugin is holding us back. We can help test if needed.

**Comment by samhibberd** [comment]
Thanks all, and great, we should have stuff to test this weekend, will post up here when ready.

**Comment by samhibberd** [comment]
Bar some styling the craft 4 version is ready to test, be great to get any feedback / issues from anyone here who has time to test: https://github.com/presseddigital/linkit/tree/develop-v4

It also includes a couple of unreleased features from the craft 3 version, if anyone wants to play with these:

- Eager loading support
- GraphQL support

We will continue with the last few tweaks and hopefully some further improvements, with a view to releasing next week.

Thanks.

**Comment by peirix** [comment]
Trying to install via composer now, but getting `Root composer.json requires presseddigital/linkit, it could not be found in any version, there may be a typo in the package name.` 

So what's the preferred way to install this beta?

**Comment by Rommert** [comment]
@peirix  in composer.json 

```"fruitstudios/linkit": "dev-develop-v4",```

**Comment by jan-dh** [comment]
Being trying it out for a while and haven't run into any issues.

**Comment by peirix** [comment]
> @peirix in composer.json
> 
> `"fruitstudios/linkit": "dev-develop-v4",`

No wonder it didn't work. Why is it released under `fruitstudios` and not `presseddigital` Can't find any reference to it in the docs either.

**Comment by jan-dh** [comment]
Was originally published by Fruitstudios and later acquired by Pressed Digital I believe. Seems that Fruitstudio now redirects to https://refiine.co.uk/.

**Comment by samhibberd** [comment]
Sorry folks details about this in the readme of the new version, it will switch up to presseddigital when released:

> :mega: **A note from the new (well sort of new) owners Pressed Digital:** At the end of 2019 Pressed Digital Ltd was sold to allow it's founders to shift 100% of their focus to the, now not so side project, findarace.com. As a part of the deal we retained ownership of all Craft plugins and are committed to make them even more awesome. With findarace.com being all Craft, this aligns really nicely, and as a little silver lining we should now finally have some time to launch some of our unreleased plugins!

Bar a couple of GQL bugs that we have run into, looking good for getting this released asap.

**Comment by rene-haefliger** [comment]
Hello, when will the plugin be final available for Craft 4?

**Comment by DynamiteGoesBoom** [comment]
Is there any update on when the Craft 4 version will be ready? Thanks gang for this awesome plugin!

**Comment by CreateSean** [comment]
This plugin is the only thing holding me back from updating a few sites. Any update?

**Comment by ben-callaway** [comment]
Thanks @CreateSean @DynamiteGoesBoom @rene-haefliger it’s in final testing and the plan is to release early next week! Thanks again for the patience 👍👍

**Comment by DynamiteGoesBoom** [comment]
Any update on this?

**Comment by ben-callaway** [comment]
Craft 4 version released: https://github.com/presseddigital/linkit/releases/tag/4.0.0
